DjangoRF/homebanking/homebanking/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('clientes/', include('clientes.urls')),
    path('prestamos/', include('prestamos.urls')),
    path('cuentas/', include('cuentas.urls')),
    path('tarjetas/', include('tarjetas.urls')),
    path('homebanking/', include('principal.urls')),
    path('sucursales/', include('sucursales.urls')),
]

DjangoRF/homebanking/login/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

urlpatterns = [
    #path('', views.index, name='index'),
    path('recuperarClave/', views.recuperarClave, name='recuperarClave'),
    path('registrarse/', views.registrarse, name='registrarse'),
    # path('login/', LoginView.as_view(template_name="login/login-page.html"), name="login"),
    path('',views.iniciarSesion, name="login"),
]

DjangoRF/homebanking/prestamos/urls.py
from django.urls import path
from . import views
from .views import EliminarPrestamo, PrestamosCliente

urlpatterns = [
    path('', views.index, name='prestamos'),
    path('nuevo_prestamo/', views.prestamos, name='nuevo_prestamo'),
    path('cliente/<int:pk>', PrestamosCliente.as_view()),
    path('anular_prestamo/<int:pk>', EliminarPrestamo.as_view()),
]

DjangoRF/homebanking/prestamos/models.py
from django.db import models

# Create your models here.

class Prestamo(models.Model):
    loan_id = models.AutoField(primary_key=True)
    loan_type = models.TextField()
    loan_date = models.TextField()
    loan_total = models.IntegerField()
    customer_id = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'prestamo'

class Cliente(models.Model):
    customer_id = models.AutoField(primary_key=True)
    customer_name = models.TextField()
    customer_surname = models.TextField()  # This field type is a guess.
    customer_dni = models.TextField(db_column='customer_DNI')  # Field name made lowercase.
    dob = models.TextField(blank=True, null=True)
    branch_id = models.IntegerField()
    tipo_cliente = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'cliente'
    
class UserCliente(models.Model):
    id_user = models.IntegerField()
    id_cliente = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'user_cliente'

class TiposCliente(models.Model):
    tipo_cliente_id = models.AutoField(primary_key=True, blank=True)
    tipo_cliente = models.TextField()

    class Meta:
        managed = False
        db_table = 'tipos_cliente'

class Cuenta(models.Model):
    account_id = models.AutoField(primary_key=True)
    customer_id = models.IntegerField()
    balance = models.IntegerField()
    iban = models.TextField()
    tipo_cuenta = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'cuenta'

DjangoRF/homebanking/prestamos/forms.py
from locale import format_string
from django import forms
from datetime import timezone
from .models import Prestamo


class PrestamosForm(forms.ModelForm):
    class Meta:
        model = Prestamo
        fields = ['loan_type', 'loan_total']

DjangoRF/homebanking/prestamos/views.py
from datetime import datetime
from django.shortcuts import render, redirect
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from .models import TiposCliente
from prestamos.models import Prestamo, Cliente,  UserCliente, Cuenta
from .forms import PrestamosForm
from .serializers import PrestamoSerializer
from rest_framework.permissions import IsAdminUser
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework import status

# Create your views here.
class PrestamosCliente(APIView):
    permission_classes = [IsAdminUser]
    def get(self,request, pk):
        prestamosCliente = Prestamo.objects.filter(customer_id=pk)
        serializer = PrestamoSerializer(prestamosCliente, many=True)
        return Response(serializer.data, status=status.HTTP_200_OK)

    def post(self, request, pk, format=None):
        serializer = PrestamoSerializer(data=request.data)
        if serializer.is_valid():
            monto = serializer.validated_data.get('loan_total')
            id = serializer.validated_data.get('customer_id')
            actualizarBalanceCliente(id, monto)
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

class EliminarPrestamo(APIView):
    permission_classes = [IsAdminUser]

    def get(self,request, pk):
        prestamo = Prestamo.objects.filter(loan_id=pk)
        serializer = PrestamoSerializer(prestamo, many=True)
        return Response(serializer.data, status=status.HTTP_200_OK)

    def delete(self, request, pk):
        prestamo = Prestamo.objects.filter(pk=pk).first()
        if prestamo:
            serializer = PrestamoSerializer(prestamo)
            monto = serializer.data['loan_total']
            id = serializer.data['customer_id']
            restarBalanceCliente(id, monto)
            prestamo.delete()
            return Response(serializer.data, status=status.HTTP_200_OK)
        return Response(status=status.HTTP_404_NOT_FOUND)

def index(request): 
    prestamos = Prestamo.objects.all().values()
    userID = request.user.id
    if userID is not None:
        idCliente = obtenerClienteId(userID)
        prestamosDelCliente = prestamos.filter(customer_id = idCliente)
        context = { 'prestamos' : prestamosDelCliente , 'userID' : userID }
        if len(prestamosDelCliente) == 0:
            messages.info(request, 'No tiene préstamos.')
    else: 
        context = { 'prestamos' : prestamos, 'userID' : userID }
    template = loader.get_template('prestamos/index.html')
    return HttpResponse(template.render(context, request))

def prestamos(request):
    if request.method == "POST":
        forms = PrestamosForm(request.POST)
        montoPrestamo = request.POST['loan_total']
        userID = request.user.id
        clienteID = obtenerClienteId(userID)
        tipoClienteID = obtenerTipoClienteID(clienteID)
        if forms.is_valid():
            prestamo = forms.save(commit=False)
            if (tipoClienteID == 1 and prestamo.loan_total <= 100000 ):
                prestamo_aprobado(prestamo, clienteID,montoPrestamo)
                return HttpResponseRedirect(reverse('prestamos'))
            elif (tipoClienteID == 2 and prestamo.loan_total <= 300000):
                prestamo_aprobado(prestamo, clienteID, montoPrestamo)
                return HttpResponseRedirect(reverse('prestamos'))
            elif (tipoClienteID == 3 and prestamo.loan_total <= 500000):
                prestamo_aprobado(prestamo, clienteID, montoPrestamo)
                return HttpResponseRedirect(reverse('prestamos'))
            else :
                tipoCliente = obtenerTipoCliente(tipoClienteID)
                messages.error(request, "No cumple con los requisitos para pedir un préstamo de ese monto.")
                messages.error(request, f"Usted es cliente {tipoCliente}")
                if (tipoClienteID == 1): messages.error(request, "Puede pedir hasta $100.000")
                if (tipoClienteID == 2): messages.error(request, "Puede pedir hasta $300.000")
                if (tipoClienteID == 3): messages.error(request, "Puede pedir hasta $500.000")
    else:
        forms = PrestamosForm()
    return render(request, "Prestamos/prestamos.html", {"forms": forms})

def prestamo_aprobado(prestamo, clienteID, montoPrestamo):
    prestamo.customer_id = clienteID
    prestamo.loan_date = datetime.now().date()
    prestamo.save()
    actualizarBalanceCliente(clienteID, montoPrestamo)
   
def actualizarBalanceCliente(clienteID, montoPrestamo):
    cuentas = Cuenta.objects.filter(customer_id = clienteID)
    montoFinal = montoPrestamo
    for x in cuentas:
        balanceAnterior = x.balance
        x.balance = int(balanceAnterior) + int(montoFinal)
        x.save()

def restarBalanceCliente(clienteID, montoPrestamo):
    cuentas = Cuenta.objects.filter(customer_id = clienteID)
    montoFinal = montoPrestamo
    for x in cuentas:
        balanceAnterior = x.balance
        x.balance = int(balanceAnterior) - int(montoFinal)
        x.save()

def obtenerClienteId(userID):
    userCliente = UserCliente.objects.filter(id_user = userID)
    for x in userCliente:
        idCliente = x.id_cliente
    return idCliente

def obtenerTipoClienteID(clienteID):
    cliente = Cliente.objects.filter(customer_id = clienteID)
    for x in cliente:
        tipo_cliente_id = x.tipo_cliente
    return tipo_cliente_id

def obtenerTipoCliente(tipo_cliente_id):
    tipoCliente = TiposCliente.objects.filter(tipo_cliente_id = tipo_cliente_id)
    for x in tipoCliente:
        tipo_cliente = x.tipo_cliente
    return tipo_cliente

DjangoRF/homebanking/prestamos/templates/prestamos/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'prestamos/images/logo icono.png' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel='stylesheet' href="{% static 'prestamos/css/prestamos.css' %}">
    <title>Prestamos</title>
</head>
<body>
  {% if userID %}   
  <div class="text-center d-flex justify-content-start align-items-center ml-4 mt-4">
    <button type="button" class="btn btn-light"><a href="../homebanking">Volver</a></button>
  </div>
  {% else %}
  <div class="text-center d-flex justify-content-start align-items-center ml-4 mt-4">
    <button type="button" class="btn btn-light"><a href="../">Volver</a></button>
  </div>
  {% endif %}
  <div class="text-center d-flex justify-content-around align-items-center mb-5">
    {% if userID %} 
    <h1>Mis préstamos</h1>
    <button type="button" class="btn btn-light"><a href="nuevo_prestamo/">Nuevo préstamo</a></button>
    {% else %}
    <h1>Préstamos</h1>
    {% endif %}
  </div>
    
    <table class="table table-striped">
        <thead class="head-table">
          <tr>
            <th scope="col">ID</th>
            <th scope="col">Tipo</th>
            <th scope="col">Fecha</th>
            <th scope="col">Total</th>
            <th scope="col">Cliente</th>
          </tr>
        </thead>
        <tbody>
          {% for prestamo in prestamos %}
          <tr>
            <th scope="row">{{ prestamo.loan_id }}</th>
            <td>{{ prestamo.loan_type }}</td>
            <td>{{ prestamo.loan_date }}</td>
            <td>{{ prestamo.loan_total }}</td>
            <td>{{ prestamo.customer_id }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      {% if messages %}
        <div class="">
            <p class="">
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            </p>    
        </div>
        {% endif %}
</body>
</html>

DjangoRF/homebanking/prestamos/templates/prestamos/prestamos.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="icon" href="{% static 'prestamos/images/logo icono.png' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel='stylesheet' href="{% static 'prestamos/css/nuevo_prestamo.css' %}">
    <title>Nuevo préstamos</title>
</head>
<body class="mt-3">
    <h2 class="title">Nuevo préstamo</h2>
    <form method="POST" class="post-form">{% csrf_token %}
        <div class="form-group">
            <label for="id_loan_type">Tipo de préstamo</label>
            <select class="form-control" name="loan_type" required="" id="id_loan_type">
                <option value="HIPOTECARIO">HIPOTECARIO</option>
                <option value="PERSONAL">PERSONAL</option>
                <option value="PRENDARIO">PRENDARIO</option>
            </select>
        </div>
        <div class="form-group">
            <label for="id_loan_total">Loan total:</label>
            <input class="form-control" type="number" name="loan_total" required="" id="id_loan_total"> 
        </div>
        <!-- {{ forms }} -->
        <button type="submit" class="botonSolicitar">Solicitar</button>
    </form>
    {% if messages %}
        <div class="errorMessages">
            <p class="errorMessages_title">La solicitud no fue procesada</p>
            {% for message in messages %}
                <div class="errorMessages_list">
                    <img src="{% static 'prestamos/images/cruz.png' %}" alt="Cruz de error" width="16">
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                </div>      
            {% endfor %}
            </p>    
        </div>
    {% endif %}
</body>
</html>